-- Add driver authentication columns for mobile app onboarding
-- Run this on RDS to add access code and app authentication support

-- Add access code columns to drivers table
ALTER TABLE logistics.drivers 
ADD COLUMN IF NOT EXISTS access_code VARCHAR(8),
ADD COLUMN IF NOT EXISTS access_code_generated_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS access_code_used_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS app_approved BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS app_first_login_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS app_last_login_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS push_notification_token TEXT;

-- Create index for quick access code lookup
CREATE INDEX IF NOT EXISTS idx_drivers_access_code ON logistics.drivers(access_code) WHERE access_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_drivers_phone ON logistics.drivers(phone, tenant_id);

-- Create driver sessions table for persistent login
CREATE TABLE IF NOT EXISTS logistics.driver_sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL,
    driver_id UUID NOT NULL REFERENCES logistics.drivers(driver_id) ON DELETE CASCADE,
    token VARCHAR(255) NOT NULL UNIQUE,
    device_info JSONB,
    ip_address VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_active_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    is_active BOOLEAN DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_driver_sessions_token ON logistics.driver_sessions(token) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_driver_sessions_driver ON logistics.driver_sessions(driver_id, is_active);

COMMENT ON COLUMN logistics.drivers.access_code IS 'Unique 6-digit code for driver onboarding - generated by admin';
COMMENT ON COLUMN logistics.drivers.app_approved IS 'Whether driver is approved to use mobile app';
COMMENT ON TABLE logistics.driver_sessions IS 'Tracks driver mobile app sessions for persistent login';
