// ============================================================================
// ACCOUNTING AUTOMATION - TYPE DEFINITIONS
// 100% automated double-entry with AI validation
// ============================================================================

// ---------------------------------------------------------------------------
// CHART OF ACCOUNTS
// ---------------------------------------------------------------------------
export type AccountType = 'asset' | 'liability' | 'equity' | 'revenue' | 'expense';
export type AccountSubtype = 
  | 'current_asset' | 'fixed_asset' | 'accounts_receivable' | 'inventory' | 'prepaid'
  | 'current_liability' | 'long_term_liability' | 'accounts_payable' | 'accrued'
  | 'common_stock' | 'retained_earnings' | 'other_equity'
  | 'operating_revenue' | 'other_revenue'
  | 'cost_of_goods' | 'operating_expense' | 'other_expense';

export interface ChartOfAccount {
  accountId: string;
  tenantId: string;
  entityId?: string;
  accountCode: string;
  accountName: string;
  accountType: AccountType;
  accountSubtype?: AccountSubtype;
  parentAccountId?: string;
  currencyCode: string;
  isActive: boolean;
  isSystemAccount: boolean;
  normalBalance: 'debit' | 'credit';
  description?: string;
  taxCode?: string;
  reconciliationRequired: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// ---------------------------------------------------------------------------
// JOURNAL ENTRIES
// ---------------------------------------------------------------------------
export type JournalEntryType = 'standard' | 'adjusting' | 'closing' | 'reversing' | 'auto';
export type JournalEntryStatus = 'draft' | 'pending_approval' | 'posted' | 'reversed';

export interface JournalEntry {
  entryId: string;
  tenantId: string;
  entityId?: string;
  entryNumber: string;
  entryDate: Date;
  postedDate?: Date;
  periodId?: string;
  entryType: JournalEntryType;
  sourceModule?: string;
  sourceDocumentId?: string;
  sourceDocumentType?: string;
  description: string;
  aiExplanation?: string;
  aiConfidenceScore?: number;
  totalDebit: number;
  totalCredit: number;
  currencyCode: string;
  exchangeRate: number;
  status: JournalEntryStatus;
  isBalanced: boolean;
  reversalOfEntryId?: string;
  reversedByEntryId?: string;
  approvedBy?: string;
  approvedAt?: Date;
  postedBy?: string;
  createdBy?: string;
  createdAt: Date;
  updatedAt: Date;
  entryHash?: string;
  previousHash?: string;
  lines?: JournalEntryLine[];
}

export interface JournalEntryLine {
  lineId: string;
  entryId: string;
  lineNumber: number;
  accountId: string;
  account?: ChartOfAccount;
  debitAmount: number;
  creditAmount: number;
  currencyCode: string;
  baseDebit: number;
  baseCredit: number;
  description?: string;
  costCenterId?: string;
  projectId?: string;
  departmentId?: string;
  dimension1?: string;
  dimension2?: string;
  dimension3?: string;
  taxCode?: string;
  taxAmount: number;
  reconciled: boolean;
  reconciliationId?: string;
  createdAt: Date;
}

export interface CreateJournalEntryRequest {
  tenantId: string;
  entityId?: string;
  entryDate: Date;
  entryType: JournalEntryType;
  sourceModule?: string;
  sourceDocumentId?: string;
  sourceDocumentType?: string;
  description: string;
  currencyCode?: string;
  lines: CreateJournalLineRequest[];
  autoPost?: boolean;
}

export interface CreateJournalLineRequest {
  accountId: string;
  debitAmount?: number;
  creditAmount?: number;
  description?: string;
  costCenterId?: string;
  projectId?: string;
  departmentId?: string;
  taxCode?: string;
}

// ---------------------------------------------------------------------------
// ACCOUNTS RECEIVABLE
// ---------------------------------------------------------------------------
export type ARInvoiceStatus = 'draft' | 'sent' | 'partially_paid' | 'paid' | 'overdue' | 'written_off';
export type CollectionStatus = 'none' | 'reminder_1' | 'reminder_2' | 'reminder_3' | 'escalated' | 'collections';

export interface ARInvoice {
  invoiceId: string;
  tenantId: string;
  invoiceNumber: string;
  customerId: string;
  customerName?: string;
  invoiceDate: Date;
  dueDate: Date;
  currencyCode: string;
  subtotal: number;
  taxAmount: number;
  totalAmount: number;
  amountPaid: number;
  amountDue: number;
  status: ARInvoiceStatus;
  autoGenerated: boolean;
  sourceType?: string;
  sourceId?: string;
  aiPaymentPredictionDate?: Date;
  aiPaymentProbability?: number;
  aiRiskScore?: number;
  collectionStatus: CollectionStatus;
  lastReminderDate?: Date;
  nextActionDate?: Date;
  journalEntryId?: string;
  terms?: string;
  poNumber?: string;
  notes?: string;
  createdBy?: string;
  createdAt: Date;
  updatedAt: Date;
  lines?: ARInvoiceLine[];
}

export interface ARInvoiceLine {
  lineId: string;
  invoiceId: string;
  lineNumber: number;
  itemCode?: string;
  description: string;
  quantity: number;
  unitPrice: number;
  discountPercent: number;
  taxCode?: string;
  taxRate: number;
  lineTotal: number;
  revenueAccountId?: string;
  costCenterId?: string;
  createdAt: Date;
}

export interface CreateARInvoiceRequest {
  tenantId: string;
  customerId: string;
  invoiceDate?: Date;
  dueDate?: Date;
  currencyCode?: string;
  terms?: string;
  poNumber?: string;
  notes?: string;
  lines: CreateARInvoiceLineRequest[];
  autoGenerated?: boolean;
  sourceType?: string;
  sourceId?: string;
}

export interface CreateARInvoiceLineRequest {
  itemCode?: string;
  description: string;
  quantity: number;
  unitPrice: number;
  discountPercent?: number;
  taxCode?: string;
  revenueAccountId?: string;
  costCenterId?: string;
}

// ---------------------------------------------------------------------------
// AR PAYMENTS & SMART MATCHING
// ---------------------------------------------------------------------------
export type PaymentMethod = 'wire' | 'check' | 'card' | 'ach' | 'cash';
export type PaymentStatus = 'received' | 'applied' | 'bounced' | 'refunded';
export type MatchMethod = 'exact' | 'fuzzy_amount' | 'fuzzy_reference' | 'ai_predicted';

export interface ARPayment {
  paymentId: string;
  tenantId: string;
  paymentNumber: string;
  customerId: string;
  customerName?: string;
  paymentDate: Date;
  amount: number;
  currencyCode: string;
  paymentMethod?: PaymentMethod;
  referenceNumber?: string;
  bankAccountId?: string;
  status: PaymentStatus;
  autoMatched: boolean;
  matchConfidence?: number;
  matchMethod?: MatchMethod;
  unallocatedAmount: number;
  journalEntryId?: string;
  notes?: string;
  createdBy?: string;
  createdAt: Date;
  applications?: ARPaymentApplication[];
}

export interface ARPaymentApplication {
  applicationId: string;
  paymentId: string;
  invoiceId: string;
  invoiceNumber?: string;
  appliedAmount: number;
  discountTaken: number;
  writeOffAmount: number;
  applicationDate: Date;
  autoApplied: boolean;
  createdAt: Date;
}

export interface SmartMatchResult {
  invoiceId: string;
  invoiceNumber: string;
  invoiceAmount: number;
  amountDue: number;
  matchConfidence: number;
  matchMethod: MatchMethod;
  matchReasons: string[];
}

// ---------------------------------------------------------------------------
// ACCOUNTS PAYABLE
// ---------------------------------------------------------------------------
export type APInvoiceStatus = 'pending' | 'approved' | 'scheduled' | 'paid' | 'disputed' | 'void';
export type MatchStatus = 'pending' | 'matched' | 'exception' | 'override';

export interface APInvoice {
  invoiceId: string;
  tenantId: string;
  invoiceNumber: string;
  internalReference?: string;
  vendorId: string;
  vendorName?: string;
  invoiceDate: Date;
  receivedDate: Date;
  dueDate: Date;
  currencyCode: string;
  subtotal: number;
  taxAmount: number;
  totalAmount: number;
  amountPaid: number;
  amountDue: number;
  status: APInvoiceStatus;
  ocrProcessed: boolean;
  ocrConfidence?: number;
  ocrRawData?: Record<string, any>;
  originalDocumentUrl?: string;
  poId?: string;
  receiptId?: string;
  matchStatus: MatchStatus;
  matchVariance: number;
  autoMatched: boolean;
  paymentTerms?: string;
  discountDate?: Date;
  discountPercent: number;
  scheduledPaymentDate?: Date;
  paymentPriority: number;
  journalEntryId?: string;
  approvalStatus: string;
  approvedBy?: string;
  approvedAt?: Date;
  notes?: string;
  createdBy?: string;
  createdAt: Date;
  updatedAt: Date;
  lines?: APInvoiceLine[];
}

export interface APInvoiceLine {
  lineId: string;
  invoiceId: string;
  lineNumber: number;
  itemCode?: string;
  description: string;
  quantity: number;
  unitPrice: number;
  taxCode?: string;
  taxRate: number;
  lineTotal: number;
  expenseAccountId?: string;
  costCenterId?: string;
  projectId?: string;
  poLineId?: string;
  receiptLineId?: string;
  quantityMatched: number;
  createdAt: Date;
}

export interface OCRResult {
  confidence: number;
  vendorName?: string;
  invoiceNumber?: string;
  invoiceDate?: Date;
  dueDate?: Date;
  totalAmount?: number;
  taxAmount?: number;
  lineItems: OCRLineItem[];
  rawText: string;
}

export interface OCRLineItem {
  description: string;
  quantity?: number;
  unitPrice?: number;
  amount?: number;
  confidence: number;
}

export interface ThreeWayMatchResult {
  matched: boolean;
  poMatched: boolean;
  receiptMatched: boolean;
  priceVariance: number;
  quantityVariance: number;
  exceptions: ThreeWayMatchException[];
}

export interface ThreeWayMatchException {
  type: 'price' | 'quantity' | 'missing_po' | 'missing_receipt' | 'duplicate';
  description: string;
  severity: 'warning' | 'error';
  lineNumber?: number;
}

// ---------------------------------------------------------------------------
// CASH MANAGEMENT
// ---------------------------------------------------------------------------
export interface BankAccount {
  bankAccountId: string;
  tenantId: string;
  entityId?: string;
  accountName: string;
  accountNumber: string;
  routingNumber?: string;
  swiftCode?: string;
  iban?: string;
  bankName: string;
  bankAddress?: string;
  currencyCode: string;
  accountType?: string;
  glAccountId?: string;
  currentBalance: number;
  availableBalance: number;
  lastReconciledDate?: Date;
  lastSyncAt?: Date;
  isActive: boolean;
  autoSyncEnabled: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface BankTransaction {
  transactionId: string;
  tenantId: string;
  bankAccountId: string;
  transactionDate: Date;
  postDate?: Date;
  amount: number;
  runningBalance?: number;
  transactionType?: string;
  description?: string;
  referenceNumber?: string;
  checkNumber?: string;
  category?: string;
  aiCategorized: boolean;
  aiCategoryConfidence?: number;
  matched: boolean;
  matchType?: string;
  matchedDocumentId?: string;
  reconciled: boolean;
  reconciliationId?: string;
  fraudScore: number;
  fraudFlags?: Record<string, any>;
  reviewed: boolean;
  reviewedBy?: string;
  source: string;
  rawData?: Record<string, any>;
  createdAt: Date;
}

export interface CashPosition {
  asOfDate: Date;
  totalBalance: number;
  byAccount: AccountBalance[];
  byCurrency: CurrencyBalance[];
  byEntity: EntityBalance[];
}

export interface AccountBalance {
  bankAccountId: string;
  accountName: string;
  bankName: string;
  currencyCode: string;
  currentBalance: number;
  availableBalance: number;
}

export interface CurrencyBalance {
  currencyCode: string;
  balance: number;
  balanceUSD: number;
}

export interface EntityBalance {
  entityId: string;
  entityName: string;
  balance: number;
  balanceUSD: number;
}

// ---------------------------------------------------------------------------
// CASH FORECASTING
// ---------------------------------------------------------------------------
export interface CashForecast {
  forecastId: string;
  tenantId: string;
  forecastDate: Date;
  forecastHorizonDays: number;
  generatedAt: Date;
  modelVersion?: string;
  accuracyScore?: number;
  openingBalance: number;
  forecastedInflows: number;
  forecastedOutflows: number;
  forecastedClosingBalance: number;
  balanceLowerBound: number;
  balanceUpperBound: number;
  confidenceLevel: number;
  forecastDetails: DailyForecast[];
  assumptions: ForecastAssumption[];
  riskFactors: RiskFactor[];
  createdAt: Date;
}

export interface DailyForecast {
  date: Date;
  openingBalance: number;
  inflows: ForecastCategory[];
  outflows: ForecastCategory[];
  closingBalance: number;
  confidence: number;
}

export interface ForecastCategory {
  category: string;
  amount: number;
  confidence: number;
  source?: string;
}

export interface ForecastAssumption {
  name: string;
  value: string | number;
  impact: 'high' | 'medium' | 'low';
}

export interface RiskFactor {
  name: string;
  description: string;
  probability: number;
  impact: number;
  mitigation?: string;
}

// ---------------------------------------------------------------------------
// FRAUD DETECTION
// ---------------------------------------------------------------------------
export interface FraudAlert {
  alertId: string;
  transactionId: string;
  alertType: FraudAlertType;
  severity: 'low' | 'medium' | 'high' | 'critical';
  score: number;
  description: string;
  indicators: FraudIndicator[];
  status: 'new' | 'investigating' | 'confirmed' | 'dismissed';
  assignedTo?: string;
  resolvedAt?: Date;
  resolution?: string;
  createdAt: Date;
}

export type FraudAlertType = 
  | 'unusual_amount'
  | 'unusual_timing'
  | 'unusual_vendor'
  | 'duplicate_payment'
  | 'round_amount'
  | 'split_transaction'
  | 'velocity_anomaly'
  | 'behavioral_anomaly';

export interface FraudIndicator {
  indicator: string;
  value: string | number;
  threshold: string | number;
  weight: number;
}

// ---------------------------------------------------------------------------
// GLOBAL COMPLIANCE
// ---------------------------------------------------------------------------
export interface TaxJurisdiction {
  jurisdictionId: string;
  tenantId: string;
  countryCode: string;
  regionCode?: string;
  jurisdictionName: string;
  taxAuthority?: string;
  hasVat: boolean;
  hasGst: boolean;
  hasSalesTax: boolean;
  hasWithholding: boolean;
  standardRate?: number;
  reducedRate?: number;
  filingFrequency: 'monthly' | 'quarterly' | 'annually';
  filingDeadlineDay: number;
  electronicFilingRequired: boolean;
  taxRegistrationNumber?: string;
  registrationDate?: Date;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface ComplianceReport {
  reportId: string;
  tenantId: string;
  entityId?: string;
  jurisdictionId: string;
  reportType: string;
  periodStart: Date;
  periodEnd: Date;
  filingDeadline: Date;
  status: 'draft' | 'generated' | 'reviewed' | 'submitted' | 'accepted' | 'rejected';
  reportData: Record<string, any>;
  calculatedTaxDue: number;
  adjustments: number;
  finalAmount: number;
  filedAt?: Date;
  filedBy?: string;
  filingReference?: string;
  authorityResponse?: Record<string, any>;
  generationLog?: Record<string, any>;
  createdAt: Date;
  updatedAt: Date;
}

// ---------------------------------------------------------------------------
// MULTI-ENTITY & CONSOLIDATION
// ---------------------------------------------------------------------------
export interface LegalEntity {
  entityId: string;
  tenantId: string;
  entityCode: string;
  entityName: string;
  parentEntityId?: string;
  countryCode: string;
  baseCurrency: string;
  fiscalYearEndMonth: number;
  fiscalYearEndDay: number;
  consolidationMethod?: 'full' | 'proportional' | 'equity' | 'none';
  ownershipPercent: number;
  isActive: boolean;
  isEliminationsEntity: boolean;
  createdAt: Date;
  updatedAt: Date;
  children?: LegalEntity[];
}

export interface ConsolidatedFinancials {
  asOfDate: Date;
  baseCurrency: string;
  entities: EntityFinancials[];
  eliminations: EliminationEntry[];
  consolidated: FinancialStatements;
}

export interface EntityFinancials {
  entityId: string;
  entityName: string;
  currency: string;
  statements: FinancialStatements;
  translatedStatements: FinancialStatements;
}

export interface FinancialStatements {
  balanceSheet: BalanceSheet;
  incomeStatement: IncomeStatement;
  cashFlow: CashFlowStatement;
}

export interface BalanceSheet {
  asOfDate: Date;
  assets: BalanceSheetSection;
  liabilities: BalanceSheetSection;
  equity: BalanceSheetSection;
  totalAssets: number;
  totalLiabilities: number;
  totalEquity: number;
}

export interface BalanceSheetSection {
  items: FinancialLineItem[];
  total: number;
}

export interface IncomeStatement {
  periodStart: Date;
  periodEnd: Date;
  revenue: IncomeStatementSection;
  costOfGoodsSold: IncomeStatementSection;
  grossProfit: number;
  operatingExpenses: IncomeStatementSection;
  operatingIncome: number;
  otherIncomeExpense: IncomeStatementSection;
  incomeBeforeTax: number;
  taxExpense: number;
  netIncome: number;
}

export interface IncomeStatementSection {
  items: FinancialLineItem[];
  total: number;
}

export interface CashFlowStatement {
  periodStart: Date;
  periodEnd: Date;
  operatingActivities: CashFlowSection;
  investingActivities: CashFlowSection;
  financingActivities: CashFlowSection;
  netCashFlow: number;
  beginningCash: number;
  endingCash: number;
}

export interface CashFlowSection {
  items: FinancialLineItem[];
  total: number;
}

export interface FinancialLineItem {
  accountCode: string;
  accountName: string;
  amount: number;
  priorPeriodAmount?: number;
  variance?: number;
  variancePercent?: number;
}

export interface EliminationEntry {
  description: string;
  fromEntityId: string;
  toEntityId: string;
  amount: number;
  accountCode: string;
}

// ---------------------------------------------------------------------------
// AUTOMATION RULES
// ---------------------------------------------------------------------------
export type AutomationRuleType = 'auto_journal' | 'auto_invoice' | 'payment_match' | 'categorization';
export type TriggerEvent = 
  | 'shipment_delivered'
  | 'invoice_received'
  | 'payment_received'
  | 'fuel_transaction_created'
  | 'expense_submitted'
  | 'payroll_processed';

export interface AutomationRule {
  ruleId: string;
  tenantId: string;
  ruleName: string;
  ruleType: AutomationRuleType;
  triggerEvent: TriggerEvent;
  conditions: Record<string, any>;
  actions: Record<string, any>;
  priority: number;
  isActive: boolean;
  errorHandling: 'queue' | 'skip' | 'alert';
  lastTriggeredAt?: Date;
  triggerCount: number;
  successCount: number;
  failureCount: number;
  createdBy?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface AutomationLog {
  logId: string;
  tenantId: string;
  ruleId: string;
  triggerEvent: string;
  sourceDocumentType?: string;
  sourceDocumentId?: string;
  status: 'success' | 'failed' | 'skipped' | 'queued';
  resultDocumentType?: string;
  resultDocumentId?: string;
  executionTimeMs: number;
  errorMessage?: string;
  details?: Record<string, any>;
  createdAt: Date;
}

// ---------------------------------------------------------------------------
// AI FEATURES
// ---------------------------------------------------------------------------
export interface AIJournalExplanation {
  entryId: string;
  plainLanguageExplanation: string;
  accountingRationale: string;
  affectedStatements: string[];
  complianceNotes?: string[];
  confidence: number;
}

export interface AIPaymentPrediction {
  invoiceId: string;
  predictedPaymentDate: Date;
  probability: number;
  factors: PredictionFactor[];
  recommendedAction?: string;
}

export interface PredictionFactor {
  factor: string;
  impact: 'positive' | 'negative' | 'neutral';
  weight: number;
  description: string;
}

export interface AICategorization {
  transactionId: string;
  suggestedCategory: string;
  suggestedAccountId: string;
  confidence: number;
  alternativeCategories: CategorySuggestion[];
  reasoning: string;
}

export interface CategorySuggestion {
  category: string;
  accountId: string;
  confidence: number;
}
