import { Pool } from 'pg';

/**
 * Driver Authentication Migration
 * Adds columns for mobile app onboarding and creates sessions table
 */
export async function runDriverAuthMigration(pool: Pool): Promise<void> {
  console.log('🚗 Running Driver Authentication migration...');

  try {
    // Add access code and app auth columns to drivers table
    await pool.query(`
      ALTER TABLE logistics.drivers 
      ADD COLUMN IF NOT EXISTS access_code VARCHAR(8),
      ADD COLUMN IF NOT EXISTS access_code_generated_at TIMESTAMP,
      ADD COLUMN IF NOT EXISTS access_code_used_at TIMESTAMP,
      ADD COLUMN IF NOT EXISTS app_approved BOOLEAN DEFAULT false,
      ADD COLUMN IF NOT EXISTS app_first_login_at TIMESTAMP,
      ADD COLUMN IF NOT EXISTS app_last_login_at TIMESTAMP,
      ADD COLUMN IF NOT EXISTS push_notification_token TEXT;
    `);
    console.log('  ✓ Added driver auth columns');

    // Create indexes for quick lookup
    await pool.query(`
      CREATE INDEX IF NOT EXISTS idx_drivers_access_code 
        ON logistics.drivers(access_code) WHERE access_code IS NOT NULL;
      CREATE INDEX IF NOT EXISTS idx_drivers_phone 
        ON logistics.drivers(phone, tenant_id);
    `);
    console.log('  ✓ Created driver lookup indexes');

    // Create driver sessions table for persistent login
    await pool.query(`
      CREATE TABLE IF NOT EXISTS logistics.driver_sessions (
        session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        tenant_id UUID NOT NULL,
        driver_id UUID NOT NULL REFERENCES logistics.drivers(driver_id) ON DELETE CASCADE,
        token VARCHAR(255) NOT NULL UNIQUE,
        device_info JSONB,
        ip_address VARCHAR(45),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        last_active_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        expires_at TIMESTAMP NOT NULL,
        is_active BOOLEAN DEFAULT true
      );
    `);
    console.log('  ✓ Created driver_sessions table');

    // Create session indexes
    await pool.query(`
      CREATE INDEX IF NOT EXISTS idx_driver_sessions_token 
        ON logistics.driver_sessions(token) WHERE is_active = true;
      CREATE INDEX IF NOT EXISTS idx_driver_sessions_driver 
        ON logistics.driver_sessions(driver_id, is_active);
    `);
    console.log('  ✓ Created session indexes');

    // Add comments for documentation
    await pool.query(`
      COMMENT ON COLUMN logistics.drivers.access_code IS 'Unique code for driver mobile app onboarding - generated by admin';
      COMMENT ON COLUMN logistics.drivers.app_approved IS 'Whether driver is approved to use mobile app';
      COMMENT ON TABLE logistics.driver_sessions IS 'Tracks driver mobile app sessions for persistent login';
    `);
    console.log('  ✓ Added column comments');

    console.log('✅ Driver Authentication migration completed');

  } catch (error: any) {
    // If columns already exist, that's OK
    if (error.code === '42701') { // duplicate column error
      console.log('  ⓘ Some columns already exist - skipping');
    } else if (error.code === '42P07') { // duplicate table error
      console.log('  ⓘ Table already exists - skipping');
    } else {
      throw error;
    }
  }
}
